<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <ApplicationIcon />
    <OutputType>Library</OutputType>
    <StartupObject />
    <Win32Resource />
    <Version>0.2</Version>
    <Company>Juan Cardoso</Company>
    <Authors>Juan Cardoso</Authors>
    <Copyright>Juan Cardoso</Copyright>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <WarningLevel>0</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Fonts\FontAwesome6Free-Solid-900.otf" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Fonts\FontAwesome6Free-Solid-900.otf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FirebaseDatabase.net" Version="5.0.0" />
    <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
    <PackageReference Include="Xamarin.CommunityToolkit" Version="1.2.0" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2012" />
    <PackageReference Include="Xamarin.Essentials" Version="1.6.1" />
    <PackageReference Include="Xamarin.Forms.PancakeView" Version="2.3.0.759" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Styles\SettingsStyles.xaml.cs">
      <DependentUpon>SettingsStyles.xaml</DependentUpon>
    </Compile>
    <Compile Update="Styles\ColorsLight.xaml.cs">
      <DependentUpon>ColorsLight.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\CartDetailsPage.xaml.cs">
      <DependentUpon>CartDetailsPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\CartPage.xaml.cs">
      <DependentUpon>CartPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\CurrencySelectionPage.xaml.cs">
      <DependentUpon>CurrencySelectionPage.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Styles\WelcomeStyles.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\StartupPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Styles\AddNewCartStyles.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Styles\CartDetailsStyles.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Styles\CartStyles.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Styles\ChangedCartModeAlertStyles.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Styles\ColorsDark.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Styles\ColorsLight.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Styles\CurrencySelectionStyles.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Styles\GlobalStyles.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Styles\HomeStyles.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\AddNewCartPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\CartDetailsPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\CartPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ChangedCartModeAlertPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\CurrencySelectionPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\HomePage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\SettingsPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\WelcomePage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
  </ItemGroup>
</Project>